# Generated by Django 4.2.3 on 2023-07-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_file_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(null=True),
        ),
    ]
