# Generated by Django 4.2.3 on 2023-08-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_file_shared_with_alter_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='shared_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.file'),
        ),
    ]
