# Generated by Django 4.2.3 on 2023-08-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_file_shared_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_opened_file',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
